export enum Limit {
    MinQuestionsNumber = 1,
    MinChoicesNumber = 2,
    MaxChoicesNumber = 4,
    MinGoodChoices = 1,
    MinBadChoices = 1,
    MinPoints = 10,
    MaxPoints = 100,
    MaxQuestionLength = 300,
    MaxChoiceLength = 100,
    MaxTitleLength = 100,
    MaxDescriptionLength = 500,
    MaxDuration = 60,
    MinDuration = 10,
    MaxAnswerLength = 150,
    MaxNameLength = 20,
}
